apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
  namespace: bigdata
spec:
  serviceName: namenode
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9870
              name: web
            - containerPort: 9000
              name: rpc
          env:
            - name: CLUSTER_NAME
              value: "test"
          envFrom:
            - configMapRef:
                name: hadoop-env
          readinessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: namenode-data
              mountPath: /hadoop/dfs/name
  volumeClaimTemplates:
    - metadata:
        name: namenode-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
