apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: bigdata
spec:
  selector:
    app: namenode
  type: NodePort        # NodePort = reachable from your laptop's browser
  ports:
    - name: web
      port: 9870
      targetPort: 9870
      nodePort: 30870   # HDFS UI: http://<minikube-ip>:30870
    - name: rpc
      port: 9000
      targetPort: 9000
